version: '2.2'
services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:5.4.1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: "2181"
    ports:
      - "2181:2181"
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: 0
    healthcheck: 
      test: ["CMD-SHELL", "nc -zv kafka 9092" ]
      interval: 30s
      timeout: 5s
      retries: 10
  dscin:
    build: dscin/
    depends_on: 
      kafka:
        condition: service_healthy  
  thmani:
    build: thmani/
    depends_on: 
      kafka:
        condition: service_healthy  
  dscout:
    build: dscout/
    depends_on: 
      kafka:
        condition: service_healthy